### PR TITLE
Pass options through to twig

### LINKED ISSUE #22: pass twig compile params
i use cross render twig (php and js).
in php twig by default enable autoescape, in twig.js it need enable.

i create [fork witch path](https://github.com/DragorWW/twig-loader/commit/92e2775fe961a140d66cecf3bba0b464f2496b26) and use them.

How to add it params in twig-loader?
1) i can make pr with my path
or
2) pass param from loader options and create pr

### PR DESCRIPTION
**Pull request by tremby**
Closes #22

Best viewed [without seeing whitespace-only changes](https://blog.github.com/2011-10-21-github-secrets/#whitespace).

### CODE REVIEW

**Comment by tremby** [comment]
This is published as `@tremby/twig-loader`.

**Comment by tremby** [comment]
I should point out that I'm not clear on the internals of this loader, nor of twig, and so I'm not sure if any of the three places I've passed the options to twig are unnecessary.

**Comment by tremby** [comment]
It appears two of the three are not required, so I removed options being passed through in loader.js.

I also moved the options one layer deeper in the options, to make way for other possible options specific to the loader (you'll see another PR soon...)

**Comment by webberig** [comment]
I moved the options handling to a separate module to keep the loader module clean.

Merged and published this to npm as version 0.4.0.

**Pull request merged**
