### PR TITLE
Add .npmignore (in current case - for exclude the tests files)

### PR DESCRIPTION
**Pull request by uzlov**
Mb better to use npmignore, for exclude the list of files from repo?
Related issue https://github.com/zimmo-be/twig-loader/pull/59

### CODE REVIEW

**Comment by andypost** [comment]
Why it's not using suggested https://docs.npmjs.com/files/package.json#files but only npm?

**Comment by uzlov** [comment]
because, as for me, the using of .npmignore is more correct for exclude some files

**Comment by webberig** [comment]
https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d

In scenarios like this, its always better to use a whitelist pattern, and not a blacklist pattern.

Much safer to use package.json's files property to configure what is needed in npm package.

**Comment by webberig** [comment]
I just released version 0.5.5 to npm. Please verify if you still encounter issues with test files inside your project.

**Pull request closed without merging**
